## Carrega as definicoes (exchanges, filas, bindings, dlq).
management.load_definitions = /etc/rabbitmq/definitions.json

## Default vhost: /
default_vhost = /

## Heartbeat e tempos de conexao razoaveis para dev
heartbeat = 60
